name: Test and create report

on:
    push:
        branches: [master]
jobs:
    Run_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node-version }}
              cache: "npm"
          - name: update node manager
            run: npm i npm@latest
          - name: install all dependencies
            run: npm i
          - name: start docker server
            run: docker-compose -f ./selenium-4-grid.yml up -d
          - name: run wdio test
            run: npm run wdio
          - name: Get Allure history
            uses: actions/checkout@v2
            if: always()
            continue-on-error: true
            with:
              ref: gh-pages
              path: gh-pages

          - name: Generate allure report
            uses: simple-elf/allure-report-action@master
            if: always()
            id: allure-report
            with:
              allure_results: allure-results
              gh_pages: gh-pages
              allure_report: allure-report
              allure_history: allure-history
              keep_reports: 20

          - name: Upload artifact allure-report
            uses: actions/upload-artifact@v1
            if: always()
            with:
              name: allure-report
              path: ./allure-report
          - name: Deploy report
            uses: JamesIves/github-pages-deploy-action@3.1.0
            if: always()
            with:
              ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
              BRANCH: master # The branch the action should deploy to.
              FOLDER: allure-report # The folder the action should deploy.
              TARGET_FOLDER: docs